# Frontend files
location / {
    root   /frontend;
    index index.html;
    try_files   $uri    $uri/   /index.html =404;
    # Security headers, NGINX serving these responses itself
    include conf.d/includes/security_assets.conf;
}